### ISSUE TITLE
Right hand side 'instaceof' is not an object [2.0.9]

### ISSUE THREAD

**Issue by HenrijsS** [windicss/nuxt-windicss#134]
**Describe the bug**
Error when compiling with a new Nuxt *2* project
This error is only with 2.0.9. 
2.0.8. works fine.

**To Reproduce**
1. yarn create nuxt-app test
2. Select WindiCSS as a UI framework

**Expected behavior**
No problems

**Screenshots**
Here's the console output:
```zsh
 ERROR  Right-hand side of 'instanceof' is not an object                                                                                                           00:42:47

  at node_modules/nuxt-windicss/dist/index.js:62319:40
  at Array.find (<anonymous>)
  at WebpackBundler.<anonymous> (node_modules/nuxt-windicss/dist/index.js:62319:26)
  at WebpackBundler.<anonymous> (node_modules/@nuxt/kit/dist/index.js:818:25)
  at WebpackClientConfig.extendConfig (node_modules/@nuxt/webpack/dist/webpack.js:1509:37)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:1544:50)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:1708:26)
  at WebpackBundler.getWebpackConfig (node_modules/@nuxt/webpack/dist/webpack.js:2016:19)
  at WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:2023:12)
  at Builder.build (node_modules/@nuxt/builder/dist/builder.js:327:30)
  at async Object._buildDev (node_modules/@nuxt/cli/dist/cli-dev.js:107:5)
  at async Object.startDev (node_modules/@nuxt/cli/dist/cli-dev.js:65:7)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-dev.js:52:5)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)
  ```
  
  And here's the line that's mentioned in the first `at`:
  
![29CAE0CA-2682-474E-BEC8-C1A176F81B3F](https://user-images.githubusercontent.com/49265222/139341024-dd47d3e7-db82-44e1-b115-7e19b9f56dd8.png)

**Comment by xby020** [comment]
Using `yarn create nuxt-app` and choosing `windicss`, the default `package.json` set `"nuxt-windicss": "^1.1.1"`, may need fix.

**Comment by ampirzadeh** [comment]
+1
I'm having the same problem

**Comment by cmpadden** [comment]
Also confirmed this issue - running `yarn upgrade` like @ampirzadeh suggested resolved the issue!

**Comment by harlan-zw** [comment]
Thanks guys, waiting for the PR to be merged and it will resolve it.

**Comment by harlan-zw** [comment]
The base PR Is merged so this should be solved
