### ISSUE TITLE
Nuxt-Windicss + Nuxt 3 + DaisyUI plugin not working

### ISSUE THREAD

**Issue by Destaq** [windicss/nuxt-windicss#147]
**Describe the bug**
After trying to use the DaisyUI component library with Nuxt 3 + Nuxt-WindiCSS, I get the following error:

```
Nuxt CLI v3.0.0-27333388.c824905                                                                                                                     12:40:02
                                                                                                                                                     12:40:02
  > Local:    http://localhost:3000/ 
  > Network:  http://10.0.0.4:3000/

                                                                                                                                                     12:40:03
🌼 daisyUI components 1.17.1  https://github.com/saadeghi/daisyui                                                                                    12:40:03

 ERROR  [unhandledRejection] Maximum call stack size exceeded                                                                                        12:40:03

  at guessClassName (node_modules/windicss/lib/index.mjs:364:24)
  at node_modules/windicss/lib/index.mjs:367:67
  at Array.map (<anonymous>)
  at guessClassName (node_modules/windicss/lib/index.mjs:367:41)
  at node_modules/windicss/lib/index.mjs:367:67
  at Array.map (<anonymous>)
  at guessClassName (node_modules/windicss/lib/index.mjs:367:41)
  at node_modules/windicss/lib/index.mjs:367:67
  at Array.map (<anonymous>)
  at guessClassName (node_modules/windicss/lib/index.mjs:367:41)

ℹ nuxt-windicss v2.1.1 running with config: ./windi.config.js.                                                                         nuxt-windicss 12:40:03

 ERROR  Cannot start nuxt:  Maximum call stack size exceeded                                                                                         12:40:03

  at guessClassName (node_modules/windicss/lib/index.mjs:364:24)
  at node_modules/windicss/lib/index.mjs:367:67
  at Array.map (<anonymous>)
  at guessClassName (node_modules/windicss/lib/index.mjs:367:41)
  at node_modules/windicss/lib/index.mjs:367:67
  at Array.map (<anonymous>)
  at guessClassName (node_modules/windicss/lib/index.mjs:367:41)
  at node_modules/windicss/lib/index.mjs:367:67
  at Array.map (<anonymous>)
  at guessClassName (node_modules/windicss/lib/index.mjs:367:41)
```

The project works well prior to installing the component library.

**To Reproduce**
1. Clone repository [here](https://github.com/Destaq/nuxt3-windi-daisyui)
2. Uncomment the commented out `windi.config.js` that transforms the plugin.
3. See error

**Expected behavior**
DaisyUI to work well with Nuxt-WindiCSS, being able to be imported into WindiCSS.

**Comment by uyamazak** [comment]
I got the same error in the same environment (Nuxt-Windicss + Nuxt 3 + DaisyUI).

**Comment by itshizhan** [comment]
upgrade nuxt-windicss v2.2.5 is ok
