### ISSUE TITLE
TypeError: Invalid host defined options (with Nuxt 2)

### ISSUE THREAD

**Issue by lucpotage** [windicss/nuxt-windicss#156]
- nuxt 2.15.8
- nuxt-windi 2.2.2
- yarn 1.22.10
- node 16.3.1 LTS or 17.3.0

After running `yarn run dev`,  I have the following error:

````
FATAL Invalid host defined options
  at ModuleContainer.module.exports (node_modules/nuxt-windicss/index.cjs:3:3)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:239:34)
  at node_modules/@nuxt/utils/dist/utils.js:639:43
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:51:7)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)
```

I tried with a different Node version without success.

**Comment by lucpotage** [comment]
After removing both `node_modules`, `yarn.lock` and reinstalling dependencies, it worked again. There must have been a mismatch I can’t explain.
